### ISSUE TITLE
Display an image instead of placeholder

### ISSUE THREAD

**Issue by ewilan-riviere** [meilisearch/mini-dashboard#149]
Hello!

I use Meilisearch with [Laravel Scout](https://laravel.com/docs/8.x/scout), I install locally Meilisearch and everything works, I can add indexes from Laravel with Scout. On mini-dashboard, I can check these indexes, no problem.

But I have a placeholder for image.

![minidashboard](https://user-images.githubusercontent.com/48261459/136700446-aeaf80da-660f-4df3-92e4-febed2397bb1.jpg)

I would to know how to set an image in results like poster for [movies example](https://docs.meilisearch.com/learn/getting_started/quick_start.html#search).

**Comment by ewilan-riviere** [comment]
Thanks for your answer ;)

Yes, I have image. I create another example to show it.

My model here is `Author`, I use Laravel Scout options to add image to my model and it's works for meilisearch but I've a placeholder.

```php
public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'firstname' => $this->firstname,
            'lastname' => $this->lastname,
            'image' => $this->getFirstMediaUrl('authors', 'thumbnail'),
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
```

![minidashboard](https://user-images.githubusercontent.com/48261459/136822337-702269ef-b3bb-49eb-8474-55d1265cbded.jpg)

**Comment by mdubus** [comment]
Thanks for your feedback @ewilan-riviere !
I think that's because your images are in the `webp` format, which isn't currently implemented inside the Dashboard. 
Can you confirm me that all of your images are in `webp` ? I want to make sure that I'm not missing any bug here :) 
In the meanwhile, I'm going to make a PR for the `webp` format, hopping that it will fix your problem :)
