### ISSUE TITLE
Change the naming of `Private Key`

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/mini-dashboard#239]
Since v0.25.0 the term `private` key is not used anywhere. 
See [gatsby section on API keys](https://github.com/meilisearch/gatsby-plugin-meilisearch/#-add-your-meilisearch-credentials). 

Another naming, or another formulation, should be used to tell user which key to use here: 

<img width="1010" alt="Screenshot 2022-02-10 at 11 35 33" src="https://user-images.githubusercontent.com/33010418/153389630-33a685d0-f57d-4540-a29b-416863e22900.png">

Any suggestion @gmourier

**Comment by gmourier** [comment]
I think we can propose to add the master key because this modal is asked after a user has specified a master key.

Now as it is, does it make sense to ask for a key that has all rights when no writing is possible via the mini-dashboard?

The given API key, should at least have the rights to `GET /indexes`, `search`, and `/version` to guarantee the use of the mini-dashboard.

The `Default Admin API Key` fulfills this basic role well, but it forces the user to make a call on `/keys` to find it and may share it with everyone that wants to access the mini-dashboard.

In the help text at the bottom it should say something like this: "At least one API key that allows access to the meilisearch version, search and access to an index (to fetch the list of accessible indexes).

The advantage of the API Keys feature is that the user can share the dashboard with an API key dedicated to what needs to be consulted by the user or group of users and not give access to everything by default.
